#############
#	R script to make Figures 4 and S11 of Chang et al. 2019 PLoS Biology
# Figure S11. Genomic TE distribution across chromosomes. 
# Distribution of TEs (represented by different colors) along the following 
# chromosomes: A) chromosome 2; B) chromosome 3; C) chromosome 4; D) chromosome X; 
# and E) chromosome Y. Contigs from each chromosome were concatenated in order with 
# an arbitrary insertion of 100 kb of ‘N’. Distances along the x-axis are approximate.
# The order and orientation of the Y chromosome contigs is based on gene order
# (see Chang and Larracuente 2018). Each triangle corresponds to one TE, 
# where filled shapes indicate full length TEs and open shapes indicate truncated TEs.
# The vertical grey bars represent the arbitrary 100kb window inserted between contigs,
# indicating where we have gaps in our assembly. The centromere positions are set to 
# 0 for each chromosome. Chromosomes are not drawn to scale (chromosome 4 and Y are 
# enlarged). We show the genomic distribution of a sample of TEs enriched in CENP-A 
# according to our ChIPseq analysis (all except PROTOP). PROTOP are DNA transposons 
# that have not been recently active and their distribution is primarily in 
# heterochromatin. TART elements are non-LTR retroelements highly enriched at 
# telomeres, and are also moderately CENP-A enriched. DM1731 is a retroelement 
# moderately enriched for CENP-A, but not enriched in the centromere islands. 
# DOC2, G, Jockey-1 and G2/Jockey-3 are CENP-A enriched non-LTR retroelements abundant
# in the centromere islands (see Table S2 and Table S9). 
#
# By Xiaolu Wei
# Xiaolu_Wei@URMC.Rochester.edu
############## 

library(ggplot2)

#set chromosome to be plot
chromosome='4'

#input file generated by "summarize_repeat_chromosome_position.py"
infile=paste("/Users/WXL/Documents/lab/Genomics/results/TEs/summary/chromosome",chromosome,"_format_G2J3combined_newlist.summary", sep = "")
summary <- read.table(infile,sep='\t',header=T,fill=T)
points <- as.factor(summary$full)
elements <- factor(summary$element,levels=c('PROTOP','TART','R1','DM1731_I','DOC2','G','Jockey-1','G2/Jockey-3')) 
#full list("black","#56B4E9","green","orchid","dark green","pink",'gold','maroon')
# for 4, X (lack DM1731_I("orchid"))
colors_X=c("black","#56B4E9","green","dark green","pink",'gold','maroon')
colors_4=c("black","#56B4E9","green","dark green","pink",'gold','maroon')
# for 2,3,Y (lack Jockey-1(gold))
colors <- c("black","#56B4E9","green","orchid","dark green","pink",'maroon')
a <- 0.1

###
#2
###

pdf("2.pdf",width=12,height=3)
ggplot(summary, aes(x=(position_chro/1000000), y=value)) +
  
  #2 (het,cen,het,end): (23.1,23.75,30,50)
  scale_x_continuous(breaks=c(3.75,13.75,23.75,33.75,43.75),labels=c(-20,-10,0,10,20),limits=c(0,50.5)) +
  #het/eu
  #geom_rect(data=NULL,aes(xmin=23.1,xmax=30,ymin=-Inf,ymax=Inf), fill="grey87",alpha=0.01) 
  # line
  #geom_vline(xintercept=breaks,linetype="dashed",size=0.1, color="dark grey")
  #geom_vline(xintercept=starts,linetype="dashed",color="dark grey")
  # shadow
  geom_rect(data=NULL,aes(xmin=21.497588,xmax=21.497588+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=23.63915,xmax=23.63915+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=23.763711,xmax=23.763711+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=24.046726,xmax=24.046726+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=24.172034,xmax=24.172034+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=25.056931,xmax=25.056931+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=25.881751,xmax=25.881751+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=26.398648,xmax=26.398648+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=28.46519,xmax=28.46519+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  # points 
  geom_point(alpha=0.8, size=2, stroke=0.5, aes(shape=points, colour=elements, fill=elements)) +
  xlab("position on chromosome 2 (Mb)") +
  ylab("repeats") +
  scale_y_continuous(breaks=NULL) +
  scale_shape_manual(values=c(25,6), labels=c("full length", "truncated"), guide=FALSE) +
  scale_colour_manual(name="Repeats", values=colors, guide=guide_legend(override.aes = list(shape = 25, fill=colors))) +
  scale_fill_manual(guide=FALSE, values = colors) +
  # plot background
  theme(panel.background=element_rect(colour = "grey", fill = "white")) +
  # legend key background
  theme(legend.key=element_rect(colour = "white", fill = "white"))

dev.off()

###
#3
###
pdf("3.pdf",width=12,height=3)
ggplot(summary, aes(x=(position_chro/1000000), y=value)) +
  
  #3 (het,cen,het,end): (23,29.5,36,64)
  scale_x_continuous(breaks=c(9.5,19.5,29.5,39.5,49.5),labels=c(-20,-10,0,10,20),limits=c(0,64)) +
  # line
  #geom_vline(xintercept=breaks,linetype="dashed",size=0.1, color="dark grey")
  #geom_vline(xintercept=starts,linetype="dashed",size=0.5, color="dark grey")
  # shadow
  geom_rect(data=NULL,aes(xmin=24.600008,xmax=24.600008+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=24.806283,xmax=24.806283+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=26.711263,xmax=26.711263+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=27.356808,xmax=27.356808+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=27.466206,xmax=27.466206+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=28.900042,xmax=28.900042+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=29.027306,xmax=29.027306+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=29.130758,xmax=29.130758+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=29.244307,xmax=29.244307+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=29.346621,xmax=29.346621+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=29.550448,xmax=29.550448+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=29.681193,xmax=29.681193+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=29.795487,xmax=29.795487+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=29.941336,xmax=29.941336+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=30.057975,xmax=30.057975+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=30.237268,xmax=30.237268+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=30.373514,xmax=30.373514+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=30.812171,xmax=30.812171+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=31.011793,xmax=31.011793+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=33.920382,xmax=33.920382+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=35.755465,xmax=35.755465+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +  
  # points
  geom_point(alpha=0.8, size=2, stroke=0.5, aes(shape=points, colour=elements, fill=elements)) +
  xlab("position on chromosome 3 (Mb)") +
  ylab("repeats") +
  scale_y_continuous(breaks=NULL) +
  scale_shape_manual(values=c(25,6), labels=c("full length", "truncated"), guide=FALSE) +
  scale_colour_manual(name="Repeats", values=colors, guide=guide_legend(override.aes = list(shape = 25, fill=colors))) +
  scale_fill_manual(guide=FALSE, values = colors) +
  # plot background
  theme(panel.background=element_rect(colour = "grey", fill = "white")) +
  # legend key background
  theme(legend.key=element_rect(colour = "white", fill = "white"))

dev.off()

###
#4
###
pdf("4.pdf",width=2.5,height=3)
ggplot(summary, aes(x=(position_chro/1000000), y=value)) +
  
  #4 (cen,end): (0.05, 1.6)
  scale_x_continuous(breaks=c(-0.05,0.95),labels=c(0,1),limits=c(0,1.6)) +
  # line
  #geom_vline(xintercept=breaks,linetype="dashed",size=0.1, color="dark grey")
  #geom_vline(xintercept=starts,linetype="dashed",size=0.5, color="dark grey")
  #shadow
  geom_rect(data=NULL,aes(xmin=0.093914,xmax=0.093914+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  # points
  geom_point(alpha=0.8, size=2, stroke=0.5, aes(shape=points, colour=elements, fill=elements)) +
  xlab("position on chromosome 4 (Mb)") +
  ylab("repeats") +
  scale_y_continuous(breaks=NULL) +
  scale_shape_manual(values=c(25,6), labels=c("full length", "truncated"), guide=FALSE) +
  scale_colour_manual(name="Repeats", values=colors_4, guide=FALSE) +
  scale_fill_manual(guide=FALSE, values = colors_4) +
  # plot background
  theme(panel.background=element_rect(colour = "grey", fill = "white")) +
  # legend key background
  theme(legend.key=element_rect(colour = "white", fill = "white"))

dev.off()  


###
#X
###
pdf("X.pdf",width=6,height=3)
ggplot(summary, aes(x=(position_chro/1000000), y=value)) +
  
  #X (het,cen): (23.2,25.3)
  scale_x_continuous(breaks=c(5.3,15.3,25.3),labels=c(-20,-10,0),limits=c(0,25.5)) +
  # line
  #geom_vline(xintercept=breaks,linetype="dashed",size=0.1, color="dark grey")
  #geom_vline(xintercept=starts,linetype="dashed",size=0.5, color="dark grey")
  #shadow
  geom_rect(data=NULL,aes(xmin=21.906113,xmax=21.906113+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=22.541279,xmax=22.541279+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=22.994481,xmax=22.994481+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=23.114999,xmax=23.114999+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=23.948109,xmax=23.948109+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=24.08368,xmax=24.08368+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=24.623035,xmax=24.623035+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=24.838874,xmax=24.838874+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=25.006862,xmax=25.006862+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=25.124266,xmax=25.124266+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  # points
  geom_point(alpha=0.8, size=2, stroke=0.5, aes(shape=points, colour=elements, fill=elements)) +
  xlab("position on chromosome X (Mb)") +
  ylab("repeats") +
  scale_y_continuous(breaks=NULL) +
  scale_shape_manual(values=c(25,6), labels=c("full length", "truncated"), guide=FALSE) +
  scale_colour_manual(name="Repeats", values=colors_X, guide=guide_legend(override.aes = list(shape = 25, fill=colors_X))) +
  scale_fill_manual(guide=FALSE, values = colors_X) +
  # plot background
  theme(panel.background=element_rect(colour = "grey", fill = "white")) +
  # legend key background
  theme(legend.key=element_rect(colour = "white", fill = "white"))

dev.off()  


###
#Y
###
pdf("Y.pdf",width=8,height=3)
ggplot(summary, aes(x=(position_chro/1000000), y=value)) +
  
  #Y (cen,end): (10,11.3)
  scale_x_continuous(breaks=c(0,5,10),labels=c(-10,-5,0),limits=c(0,11.5)) +
  # line
  #geom_vline(xintercept=breaks,linetype="dashed",size=0.1, color="dark grey")
  #geom_vline(xintercept=starts,linetype="dashed",size=0.5, color="dark grey")
  #shadow
  geom_rect(data=NULL,aes(xmin=0.574027,xmax=0.574027+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=2.74345,xmax=2.74345+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=6.19278,xmax=6.19278+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=7.009247,xmax=7.009247+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=7.192994,xmax=7.192994+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=7.68909,xmax=7.68909+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=8.204465,xmax=8.204465+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=8.762815,xmax=8.762815+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=9.874095,xmax=9.874095+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=10.114052,xmax=10.114052+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=10.900283,xmax=10.900283+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  # points
  geom_point(alpha=0.8, size=2, stroke=0.5, aes(shape=points, colour=elements, fill=elements)) +
  xlab("position on chromosome Y (Mb)") +
  ylab("repeats") +
  scale_y_continuous(breaks=NULL) +
  scale_shape_manual(values=c(25,6), labels=c("full length", "truncated"), guide=FALSE) +
  scale_colour_manual(name="Repeats", values=colors, guide=guide_legend(override.aes = list(shape = 25, fill=colors))) +
  scale_fill_manual(guide=FALSE, values = colors) +
  # plot background
  theme(panel.background=element_rect(colour = "grey", fill = "white")) +
  # legend key background
  theme(legend.key=element_rect(colour = "white", fill = "white"))

dev.off()


#########  Just G2/Jockey-3 inset at centromere islands for Fig 4
#input file generated by "summarize_repeat_chromosome_position.py"
summary_total <- read.table("chromosomeY_format_G2J3combined.summary",sep='\t',header=T,fill=T)

#set chromosome to be plot
chromosome="Y"

#set centromere
if (chromosome=="2") {
  cen="tig00057289"
}
if (chromosome=="3") {
  cen="3R_5"
}
if (chromosome=="4") {
  cen="Contig119"
}
if (chromosome=="X") {
  cen="Contig79"
}
if (chromosome=="Y") {
  cen="Y_Contig26"
}

#just G2/Jockey-3
summary <- subset(summary_total, element=='G2/Jockey-3')

#just centromere islands
summary_cen <- subset(summary, contig==cen)


###
#2
###

points <- as.factor(summary$full)
elements <- factor(summary$element,levels=c('G2/Jockey-3')) 
colors <- c("maroon")
a <- 0.1

pdf("2_justG2J3combined.pdf",width=12,height=2)
ggplot(summary, aes(x=(position_chro/1000000), y=value)) +
  
  #2 (het,cen,het,end): (23.1,23.75,30,50)
  scale_x_continuous(breaks=c(3.75,13.75,23.75,33.75,43.75),labels=c(-20,-10,0,10,20),limits=c(0,50.5)) +
  # shadow
  geom_rect(data=NULL,aes(xmin=21.497588,xmax=21.497588+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=23.63915,xmax=23.63915+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=23.763711,xmax=23.763711+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=24.046726,xmax=24.046726+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=24.172034,xmax=24.172034+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=25.056931,xmax=25.056931+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=25.881751,xmax=25.881751+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=26.398648,xmax=26.398648+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=28.46519,xmax=28.46519+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  # points
  geom_point(alpha=0.8, size=2, stroke=0.5, aes(shape=points, colour=elements, fill=elements)) +
  xlab("position on chromosome 2 (Mb)") +
  ylab("repeats") +
  scale_y_continuous(breaks=NULL) +
  scale_shape_manual(values=c(25,6), labels=c("full length", "truncated"), guide=FALSE) +
  scale_colour_manual(name="Repeats", values=colors, guide=guide_legend(override.aes = list(shape = 25, fill=colors))) +
  scale_fill_manual(guide=FALSE, values = colors) +
  # plot background
  theme(panel.background=element_rect(colour = "grey", fill = "white")) +
  # legend key background
  theme(legend.key=element_rect(colour = "white", fill = "white"))

dev.off()


#just centromere island

points <- as.factor(summary_cen$full)
elements <- factor(summary_cen$element,levels=c('G2/Jockey-3')) 
colors <- c("maroon")
a <- 0.1

pdf("2_justG2J3combined_justCen.pdf",width=3,height=2)
ggplot(summary_cen, aes(x=(position_cen/1000), y=value)) +
  
  #Cen2 (25Kb)
  scale_x_continuous(breaks=c(-10,0,10), labels=c(-10,0,10), limits=c(-12.5,12.5)) +
  # points
  geom_point(alpha=0.8, size=2, stroke=0.5, aes(shape=points, colour=elements, fill=elements)) +
  xlab("position on Cen2 (kb)") +
  ylab("repeats") +
  scale_y_continuous(breaks=NULL) +
  scale_shape_manual(values=c(6), labels=c("truncated"), guide=FALSE) +
  scale_colour_manual(name="Repeats", values=colors, guide=guide_legend(override.aes = list(shape = 25, fill=colors))) +
  scale_fill_manual(guide=FALSE, values = colors) +
  # plot background
  theme(panel.background=element_rect(colour = "grey", fill = "white")) +
  # legend key background
  theme(legend.key=element_rect(colour = "white", fill = "white"))

dev.off()

###
#3
###

points <- as.factor(summary$full)
elements <- factor(summary$element,levels=c('G2/Jockey-3')) 
colors <- c("maroon")
a <- 0.1

pdf("3_justG2J3combined.pdf",width=12,height=3.3)
ggplot(summary, aes(x=(position_chro/1000000), y=value)) +
  
  #3 (het,cen,het,end): (23,29.5,36,64)
  scale_x_continuous(breaks=c(9.5,19.5,29.5,39.5,49.5),labels=c(-20,-10,0,10,20),limits=c(0,64)) +
  # shadow
  geom_rect(data=NULL,aes(xmin=24.600008,xmax=24.600008+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=24.806283,xmax=24.806283+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=26.711263,xmax=26.711263+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=27.356808,xmax=27.356808+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=27.466206,xmax=27.466206+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=28.900042,xmax=28.900042+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=29.027306,xmax=29.027306+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=29.130758,xmax=29.130758+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=29.244307,xmax=29.244307+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=29.346621,xmax=29.346621+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=29.550448,xmax=29.550448+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=29.681193,xmax=29.681193+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=29.795487,xmax=29.795487+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=29.941336,xmax=29.941336+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=30.057975,xmax=30.057975+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=30.237268,xmax=30.237268+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=30.373514,xmax=30.373514+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=30.812171,xmax=30.812171+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=31.011793,xmax=31.011793+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=33.920382,xmax=33.920382+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=35.755465,xmax=35.755465+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +  
  # points
  geom_point(alpha=0.8, size=2, stroke=0.5, aes(shape=points, colour=elements, fill=elements)) +
  xlab("position on chromosome 3 (Mb)") +
  ylab("repeats") +
  scale_y_continuous(breaks=NULL) +
  scale_shape_manual(values=c(25,6), labels=c("full length", "truncated"), guide=FALSE) +
  scale_colour_manual(name="Repeats", values=colors, guide=guide_legend(override.aes = list(shape = 25, fill=colors))) +
  scale_fill_manual(guide=FALSE, values = colors) +
  # plot background
  theme(panel.background=element_rect(colour = "grey", fill = "white")) +
  # legend key background
  theme(legend.key=element_rect(colour = "white", fill = "white"))

dev.off()

#just centromere island

points <- as.factor(summary_cen$full)
elements <- factor(summary_cen$element,levels=c('G2/Jockey-3')) 
colors <- c("maroon")
a <- 0.1

pdf("3_justG2J3combined_justCen.pdf",width=6,height=2)
ggplot(summary_cen, aes(x=(position_cen/1000), y=value)) +
  
  #Cen3 (103kb)
  scale_x_continuous(breaks=c(-40,-20,0,20,40), labels=c(-40,-20,0,20,40), limits=c(-52,52)) +
  # points
  geom_point(alpha=0.8, size=2, stroke=0.5, aes(shape=points, colour=elements, fill=elements)) +
  xlab("position on Cen3 (kb)") +
  ylab("repeats") +
  scale_y_continuous(breaks=NULL) +
  scale_shape_manual(values=c(6), labels=c("truncated"), guide=FALSE) +
  scale_colour_manual(name="Repeats", values=colors, guide=guide_legend(override.aes = list(shape = 25, fill=colors))) +
  scale_fill_manual(guide=FALSE, values = colors) +
  # plot background
  theme(panel.background=element_rect(colour = "grey", fill = "white")) +
  # legend key background
  theme(legend.key=element_rect(colour = "white", fill = "white"))

dev.off()

###
#4
###

points <- as.factor(summary$full)
elements <- factor(summary$element,levels=c('G2/Jockey-3')) 
colors <- c("maroon")
a <- 0.1

pdf("4_G2J3combined.pdf",width=2.5,height=2)
ggplot(summary, aes(x=(position_chro/1000000), y=value)) +
  
  #4 (cen,end): (0.05, 1.6)
  scale_x_continuous(breaks=c(-0.05,0.95),labels=c(0,1),limits=c(0,1.6)) +
  #shadow
  geom_rect(data=NULL,aes(xmin=0.093914,xmax=0.093914+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  # points
  geom_point(alpha=0.8, size=2, stroke=0.5, aes(shape=points, colour=elements, fill=elements)) +
  xlab("position on chromosome 4 (Mb)") +
  ylab("repeats") +
  scale_y_continuous(breaks=NULL) +
  scale_shape_manual(values=c(25,6), labels=c("full length", "truncated"), guide=FALSE) +
  scale_colour_manual(name="Repeats", values=colors, guide=FALSE) +
  scale_fill_manual(guide=FALSE, values = colors) +
  # plot background
  theme(panel.background=element_rect(colour = "grey", fill = "white")) +
  # legend key background
  theme(legend.key=element_rect(colour = "white", fill = "white"))

dev.off()  

#just centromere island

points <- as.factor(summary_cen$full)
elements <- factor(summary_cen$element,levels=c('G2/Jockey-3')) 
colors <- c("maroon")
a <- 0.1

pdf("4_justG2J3combined_justCen.pdf",width=6,height=2)
ggplot(summary_cen, aes(x=(position_cen/1000), y=value)) +
  
  #Cen4 (94Kb)
  scale_x_continuous(breaks=c(-40,-20,0,20,40), labels=c(-40,-20,0,20,40), limits=c(-47,47)) +
  # points
  geom_point(alpha=0.8, size=2, stroke=0.5, aes(shape=points, colour=elements, fill=elements)) +
  xlab("position on Cen4 (kb)") +
  ylab("repeats") +
  scale_y_continuous(breaks=NULL) +
  scale_shape_manual(values=c(6), labels=c("truncated"), guide=FALSE) +
  scale_colour_manual(name="Repeats", values=colors, guide=guide_legend(override.aes = list(shape = 25, fill=colors))) +
  scale_fill_manual(guide=FALSE, values = colors) +
  # plot background
  theme(panel.background=element_rect(colour = "grey", fill = "white")) +
  # legend key background
  theme(legend.key=element_rect(colour = "white", fill = "white"))

dev.off()

###
#X
###

points <- as.factor(summary$full)
elements <- factor(summary$element,levels=c('G2/Jockey-3')) 
colors <- c("maroon")
a <- 0.1

pdf("X_G2J3combined.pdf",width=6,height=2)
ggplot(summary, aes(x=(position_chro/1000000), y=value)) +
  
  #X (het,cen): (23.2,25.3)
  scale_x_continuous(breaks=c(5.3,15.3,25.3),labels=c(-20,-10,0),limits=c(0,25.5)) +
  #shadow
  geom_rect(data=NULL,aes(xmin=21.906113,xmax=21.906113+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=22.541279,xmax=22.541279+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=22.994481,xmax=22.994481+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=23.114999,xmax=23.114999+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=23.948109,xmax=23.948109+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=24.08368,xmax=24.08368+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=24.623035,xmax=24.623035+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=24.838874,xmax=24.838874+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=25.006862,xmax=25.006862+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=25.124266,xmax=25.124266+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  # points
  geom_point(alpha=0.8, size=2, stroke=0.5, aes(shape=points, colour=elements, fill=elements)) +
  xlab("position on chromosome X (Mb)") +
  ylab("repeats") +
  scale_y_continuous(breaks=NULL) +
  scale_shape_manual(values=c(25,6), labels=c("full length", "truncated"), guide=FALSE) +
  scale_colour_manual(name="Repeats", values=colors, guide=guide_legend(override.aes = list(shape = 25, fill=colors))) +
  scale_fill_manual(guide=FALSE, values = colors) +
  # plot background
  theme(panel.background=element_rect(colour = "grey", fill = "white")) +
  # legend key background
  theme(legend.key=element_rect(colour = "white", fill = "white"))

dev.off()  

#just centromere island

points <- as.factor(summary_cen$full)
elements <- factor(summary_cen$element,levels=c('G2/Jockey-3')) 
colors <- c("maroon")
a <- 0.1

pdf("X_justG2J3combined_justCen.pdf",width=5,height=2)
ggplot(summary_cen, aes(x=(position_cen/1000), y=value)) +
  
  #CenX (71Kb)
  scale_x_continuous(breaks=c(-20,0,20), labels=c(-20,0,20), limits=c(-36,36)) +
  # points
  geom_point(alpha=0.8, size=2, stroke=0.5, aes(shape=points, colour=elements, fill=elements)) +
  xlab("position on CenX (kb)") +
  ylab("repeats") +
  scale_y_continuous(breaks=NULL) +
  scale_shape_manual(values=c(6), labels=c("truncated"), guide=FALSE) +
  scale_colour_manual(name="Repeats", values=colors, guide=guide_legend(override.aes = list(shape = 25, fill=colors))) +
  scale_fill_manual(guide=FALSE, values = colors) +
  # plot background
  theme(panel.background=element_rect(colour = "grey", fill = "white")) +
  # legend key background
  theme(legend.key=element_rect(colour = "white", fill = "white"))

dev.off()

###
#Y
###

points <- as.factor(summary$full)
elements <- factor(summary$element,levels=c('G2/Jockey-3')) 
colors <- c("maroon")
a <- 0.1

pdf("Y_G2J3combined.pdf",width=8,height=2)
ggplot(summary, aes(x=(position_chro/1000000), y=value)) +
  
  #Y (cen,end): (10,11.3)
  scale_x_continuous(breaks=c(0,5,10),labels=c(-10,-5,0),limits=c(0,11.5)) +
  #shadow
  geom_rect(data=NULL,aes(xmin=0.574027,xmax=0.574027+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=2.74345,xmax=2.74345+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=6.19278,xmax=6.19278+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=7.009247,xmax=7.009247+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=7.192994,xmax=7.192994+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=7.68909,xmax=7.68909+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=8.204465,xmax=8.204465+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=8.762815,xmax=8.762815+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=9.874095,xmax=9.874095+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=10.114052,xmax=10.114052+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  geom_rect(data=NULL,aes(xmin=10.900283,xmax=10.900283+0.1,ymin=-Inf,ymax=Inf), fill="grey87",alpha=a) +
  # points
  geom_point(alpha=0.8, size=2, stroke=0.5, aes(shape=points, colour=elements, fill=elements)) +
  xlab("position on chromosome Y (Mb)") +
  ylab("repeats") +
  scale_y_continuous(breaks=NULL) +
  scale_shape_manual(values=c(25,6), labels=c("full length", "truncated"), guide=FALSE) +
  scale_colour_manual(name="Repeats", values=colors, guide=guide_legend(override.aes = list(shape = 25, fill=colors))) +
  scale_fill_manual(guide=FALSE, values = colors) +
  # plot background
  theme(panel.background=element_rect(colour = "grey", fill = "white")) +
  # legend key background
  theme(legend.key=element_rect(colour = "white", fill = "white"))

dev.off()

#just centromere island

points <- as.factor(summary_cen$full)
elements <- factor(summary_cen$element,levels=c('G2/Jockey-3')) 
colors <- c("maroon")
a <- 0.1

pdf("Y_justG2J3combined_justCen.pdf",width=8.5,height=2)
ggplot(summary_cen, aes(x=(position_cen/1000), y=value)) +
  
  #CenY (140Kb)
  scale_x_continuous(breaks=c(-60,-40,-20,0,20,40,60), labels=c(-60,-40,-20,0,20,40,60), limits=c(-70,70)) +
  # points
  geom_point(alpha=0.8, size=2, stroke=0.5, aes(shape=points, colour=elements, fill=elements)) +
  xlab("position on CenY (kb)") +
  ylab("repeats") +
  scale_y_continuous(breaks=NULL) +
  scale_shape_manual(values=c(25,6), labels=c("full length", "truncated"), guide=FALSE) +
  scale_colour_manual(name="Repeats", values=colors, guide=guide_legend(override.aes = list(shape = 25, fill=colors))) +
  scale_fill_manual(guide=FALSE, values = colors) +
  # plot background
  theme(panel.background=element_rect(colour = "grey", fill = "white")) +
  # legend key background
  theme(legend.key=element_rect(colour = "white", fill = "white"))

dev.off()


